const defaults={personOne:'Nimesh',personTwo:'Dilhani',parentOne:'Mr. & Mrs. Sunil Perera',parentTwo:'Mr. & Mrs. Ranjith Silva',date:'2026-12-27',time:'10:30',venue:'Grand Monarch, Colombo',city:'Colombo, Sri Lanka',deadline:'2026-08-10',story:"From a chance meeting to a beautiful friendship, and now to a lifetime together. We are blessed to begin this new chapter of our lives and can't wait to celebrate with you.",images:{coupleImage:'assets/nimesh-and-dilhani.webp',storyImage:'assets/wedding-venue-illustration.webp',gallery1:'assets/gallery-01.jpg',gallery2:'assets/gallery-02.jpg',gallery3:'assets/gallery-03.jpg',gallery4:'assets/gallery-04.jpg',gallery5:'assets/gallery-05.jpg',gallery6:'assets/gallery-06.jpg'}};
let settings={...defaults,images:{...defaults.images}};
const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];const editor=$('#customizer'),editorForm=$('#customizer-form'),toast=$('#toast'),saveKeyInput=$('#save-key');
function toastMessage(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}
async function readResponse(response,fallback){const text=await response.text();try{return JSON.parse(text)}catch{throw new Error(fallback||'Service is unavailable. Please try again later.')}}
function getSaveKey(){return sessionStorage.getItem('rsvp-admin-key')||''}
function rememberSaveKey(key){if(key)sessionStorage.setItem('rsvp-admin-key',key)}
function dateObject(date,time){return new Date(`${date}T${time}:00+05:30`)}
function showDate(date,short=false){return new Date(`${date}T12:00:00+05:30`).toLocaleDateString('en-GB',{day:'numeric',month:short?'short':'long',year:'numeric',timeZone:'Asia/Colombo'})}
function iso(date){return date.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z')}
function updateCalendar(){const start=dateObject(settings.date,settings.time),end=dateObject(settings.date,'23:00'),startCode=iso(start),endCode=iso(end),url=new URL('https://calendar.google.com/calendar/render');url.searchParams.set('action','TEMPLATE');url.searchParams.set('text',`${settings.personOne} & ${settings.personTwo} — Wedding Celebration`);url.searchParams.set('dates',`${startCode}/${endCode}`);url.searchParams.set('details',`Wedding celebration for ${settings.personOne} and ${settings.personTwo}.`);url.searchParams.set('location',`${settings.venue}, ${settings.city}`);$('#google-calendar').href=url.toString();return{startCode,endCode}}
function updateCountdown(){const left=Math.max(0,dateObject(settings.date,settings.time).getTime()-Date.now()),values={days:Math.floor(left/86400000),hours:Math.floor(left%86400000/3600000),minutes:Math.floor(left%3600000/60000),seconds:Math.floor(left%60000/1000)};for(const[id,value]of Object.entries(values))document.getElementById(id).textContent=String(value).padStart(2,'0')}
function applySettings(){const d=dateObject(settings.date,settings.time),day=Number(settings.date.slice(-2)),suffix=day%100>=11&&day%100<=13?'th':({1:'st',2:'nd',3:'rd'}[day%10]||'th'),[h,m]=settings.time.split(':').map(Number),time=`${(h%12)||12}:${String(m).padStart(2,'0')} ${h>=12?'PM':'AM'}`,venue=settings.venue.trim(),city=settings.city.trim();
  $('#person-one').textContent=settings.personOne;$('#person-two').textContent=settings.personTwo;$('#parent-one').textContent=settings.parentOne;$('#parent-two').textContent=settings.parentTwo;
  $('#event-weekday').textContent=d.toLocaleDateString('en-US',{weekday:'long',timeZone:'Asia/Colombo'}).toUpperCase();$('#formatted-date').innerHTML=`${day}<sup>${suffix}</sup> ${showDate(settings.date).replace(/^\d+\s*/,'')}`;$('#event-time').textContent=time;$('#venue-main').textContent=venue.toUpperCase();
  $('#venue-location').textContent=venue;$('#venue-city').textContent=city;$('#closing-names').textContent=`${settings.personTwo} & ${settings.personOne}`;$('#closing-date').textContent=showDate(settings.date);$('#closing-venue').textContent=venue;$('#story-copy').textContent=settings.story;
  $$('[data-event-date]').forEach(el=>el.textContent=showDate(settings.date,true));$$('[data-main-location]').forEach(el=>el.innerHTML=`⌖ &nbsp;${escapeText(venue)}`);
  const q=encodeURIComponent(`${venue}, ${city}`);$('#venue-map').src=`https://maps.google.com/maps?q=${q}&t=&z=12&ie=UTF8&iwloc=&output=embed`;$('#map-link').href=`https://maps.google.com/?q=${q}`;
  $('#rsvp-deadline').textContent=settings.deadline?new Date(`${settings.deadline}T12:00:00+05:30`).toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'Asia/Colombo'}).toUpperCase():'PLEASE REPLY';
  $('#couple-image').src=settings.images.coupleImage;$('#story-image').src=settings.images.storyImage;Object.keys(settings.images).filter(k=>k.startsWith('gallery')).forEach((key,i)=>{const btn=$$('[data-photo]')[i];if(btn){btn.dataset.photo=settings.images[key];btn.querySelector('img').src=settings.images[key];btn.querySelector('img').alt=`${settings.personOne} and ${settings.personTwo}, photo ${i+1}`}});
  $('#couple-image').alt=`Illustration of ${settings.personOne} and ${settings.personTwo} in wedding attire`;$('#story-image').alt=`Wedding venue illustration for ${settings.personOne} and ${settings.personTwo}`;updateCountdown();updateCalendar()}
function escapeText(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fillEditor(){for(const [key,value] of Object.entries(settings)){if(key==='images')continue;const input=editorForm.elements.namedItem(key);if(input)input.value=value}saveKeyInput.value=getSaveKey();editorForm.querySelectorAll('input[type=file]').forEach(input=>input.value='')}
async function loadSettings(){try{const response=await fetch('/api/settings',{cache:'no-store'});const result=await response.json();if(!response.ok)throw new Error(result.error||'Could not load invitation details.');settings={...defaults,...result,images:{...defaults.images,...result.images}};applySettings()}catch{applySettings()}}
loadSettings();setInterval(updateCountdown,1000);
$('#customize-open').addEventListener('click',()=>{fillEditor();editor.showModal()});$('#customizer-close').addEventListener('click',()=>editor.close());editor.addEventListener('click',e=>{if(e.target===editor)editor.close()});
function compressImage(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(reader.error);reader.onload=()=>{const img=new Image();img.onerror=()=>reject(Error('Could not read image'));img.onload=()=>{const scale=Math.min(1,1000/Math.max(img.naturalWidth,img.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.max(1,img.naturalWidth*scale);canvas.height=Math.max(1,img.naturalHeight*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/webp',.72))};img.src=reader.result};reader.readAsDataURL(file)})}
editorForm.addEventListener('submit',async e=>{e.preventDefault();const save=editorForm.querySelector('.save-customization');const saveKey=saveKeyInput.value.trim();if(!saveKey){toastMessage('Enter your save key to update the invitation.');return}save.disabled=true;save.textContent='Saving…';const data=new FormData(editorForm),next={...settings,images:{...settings.images}};for(const key of ['personOne','personTwo','parentOne','parentTwo','date','time','venue','city','deadline','story'])next[key]=String(data.get(key)||'').trim();try{for(const input of editorForm.querySelectorAll('input[type=file]'))if(input.files?.[0])next.images[input.name]=await compressImage(input.files[0]);const response=await fetch('/api/settings',{method:'PUT',headers:{'Content-Type':'application/json','x-admin-token':saveKey},body:JSON.stringify(next)}),result=await response.json();if(!response.ok)throw new Error(result.error||'Your invitation details could not be saved.');rememberSaveKey(saveKey);settings={...defaults,...result.settings,images:{...defaults.images,...result.settings.images}};applySettings();editor.close();toastMessage('Your changes are saved to the database.')}catch(error){toastMessage(error.message.includes('fetch')?'Could not reach the save service. Try again later.':error.message)}finally{save.disabled=false;save.textContent='Save changes'}});
$('#reset-customizer').addEventListener('click',async()=>{const saveKey=getSaveKey()||saveKeyInput.value.trim();if(!saveKey){toastMessage('Enter your save key before resetting the invitation.');return}try{const response=await fetch('/api/settings',{method:'DELETE',headers:{'x-admin-token':saveKey}}),result=await response.json();if(!response.ok)throw new Error(result.error||'Could not reset the invitation.');rememberSaveKey(saveKey);settings={...defaults,...result.settings,images:{...defaults.images,...result.settings.images}};fillEditor();applySettings();toastMessage('Sample invitation restored.')}catch(error){toastMessage(error.message.includes('fetch')?'Could not reach the save service. Try again later.':error.message)}});
let attending='yes',guests=1;$$('[data-attendance]').forEach(button=>button.addEventListener('click',()=>{attending=button.dataset.attendance;$$('[data-attendance]').forEach(b=>b.classList.toggle('selected',b===button));$('#guest-count').textContent=attending==='yes'?String(guests):'0';$$('.guest-counter button').forEach(b=>b.disabled=attending==='no')}));$('#increase').addEventListener('click',()=>{guests=Math.min(10,guests+1);$('#guest-count').textContent=guests});$('#decrease').addEventListener('click',()=>{guests=Math.max(1,guests-1);$('#guest-count').textContent=guests});
function getSubmissionId(){let id=localStorage.getItem('ceylon-rsvp-submission-id');if(!id){id=crypto.randomUUID();localStorage.setItem('ceylon-rsvp-submission-id',id)}return id}
$('#rsvp-form').addEventListener('submit',async e=>{e.preventDefault();const name=$('#guest-name').value.trim();if(!name)return;const button=e.currentTarget.querySelector('.submit-rsvp');button.disabled=true;button.textContent='SENDING…';$('#form-message').textContent='';try{const response=await fetch('/api/rsvp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({submissionId:getSubmissionId(),attendance:attending,guestCount:attending==='yes'?guests:0,guestName:name})}),result=await readResponse(response,'RSVP service is unavailable. Please try again later.');if(!response.ok)throw Error(result.error||'Your RSVP could not be saved.');$('#form-message').textContent=`Thank you, ${name}. Your reply has been received.`;toastMessage('Your RSVP has been added to the guest count.')}catch(error){$('#form-message').textContent=error.message.includes('fetch')?'RSVP service is unavailable. Please try again later.':error.message;toastMessage('Your reply was not saved.')}finally{button.disabled=false;button.innerHTML='RSVP NOW &nbsp; ♥'}});
const viewer=$('#photo-viewer');$$('[data-photo]').forEach(button=>button.addEventListener('click',()=>{$('#viewer-image').src=button.dataset.photo;viewer.showModal()}));$('.photo-close').addEventListener('click',()=>viewer.close());viewer.addEventListener('click',e=>{if(e.target===viewer)viewer.close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&viewer.open)viewer.close()});
$('#calendar-toggle').addEventListener('click',()=>{$('#calendar-menu').hidden=!$('#calendar-menu').hidden});$('#download-calendar').addEventListener('click',()=>{const{startCode,endCode}=updateCalendar(),ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Wedding Invitation//EN','BEGIN:VEVENT','UID:invitation-preview@local','DTSTAMP:20261007T000000Z',`DTSTART:${startCode}`,`DTEND:${endCode}`,`SUMMARY:${settings.personOne} & ${settings.personTwo} — Wedding Celebration`,`LOCATION:${settings.venue}, ${settings.city}`,'END:VEVENT','END:VCALENDAR'].join('\r\n'),blob=new Blob([ics],{type:'text/calendar;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='wedding-invitation.ics';link.click();URL.revokeObjectURL(url);$('#calendar-menu').hidden=true});
